#!/bin/sh
set -e

REPO="lix-buildkite-agent"
VERSION_FILE="Dockerfile"

BUILD_NUMBER=${BUILDKITE_BUILD_NUMBER:-local}
BRANCH=${BUILDKITE_BRANCH:-local}
BRANCH=${BRANCH//\//_}
VERSION=$(grep -m1 FROM "$VERSION_FILE" | awk -F: '{ print $2 }' | sed 's/[", ]//g')
if [ "$BRANCH" = "master" ]; then
  FULL_VERSION="$VERSION.$BUILD_NUMBER"
else
  FULL_VERSION="$VERSION.$BUILD_NUMBER-$BRANCH"
fi
DOCKER_IMAGE="local/$REPO"

if [ -n "$BUILDKITE_BUILD_NUMBER" ]; then
  buildkite-agent meta-data set "release-version" "$FULL_VERSION"
fi

cat << EOF > build.env
IMAGE_VERSION=$FULL_VERSION
IMAGE_BRANCH=$BUILDKITE_BRANCH
IMAGE_COMMIT=$BUILDKITE_COMMIT
IMAGE_REPO=$BUILDKITE_REPO
IMAGE_TAG=$BUILDKITE_TAG
IMAGE_PULL_REQUEST=$BUILDKITE_PULL_REQUEST
IMAGE_BUILT_ON_BUILTKITE=$BUILDKITE
IMAGE_BUILDKITE_BUILD_ID=$BUILDKITE_BUILD_ID
IMAGE_BUILDKITE_BUILD_URL=$BUILDKITE_BUILD_URL
IMAGE_BUILDKITE_AGENT_NAME=$BUILDKITE_AGENT_NAME
IMAGE_BUILDKITE_MESSAGE=$BUILDKITE_MESSAGE
EOF

echo "export REPO=$REPO"
echo "export BUILD_NUMBER=$BUILD_NUMBER"
echo "export BRANCH=$BRANCH"
echo "export VERSION=$VERSION"
echo "export FULL_VERSION=$FULL_VERSION"
echo "export DOCKER_IMAGE=$DOCKER_IMAGE"